# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_birth',
            field=models.DateField(default=django.utils.timezone.now, max_length=45),
            preserve_default=False,
        ),
    ]
