# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161127_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='task',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(max_length=45, null=True),
        ),
    ]
